In [13]:
import numpy as np

a= np.array([[1,2],[3,4]])
b =np.array([1,2])
(a.T*b).T

array([[1, 2],
       [6, 8]])

In [2]:
import torch
a = torch.Tensor(   [[1,2,3],
                    [4,5,6]])
b = torch.Tensor([1,-1,0])
torch.cat((a,a),dim = 1)


tensor([[1., 2., 3., 1., 2., 3.],
        [4., 5., 6., 4., 5., 6.]])

In [10]:
w1 = torch.nn.Parameter(torch.randn(10,64), requires_grad=True)

In [29]:
a = torch.rand(10,64)
b = torch.rand(10,64)
c = a.T @ b
c.shape
import torch.nn.functional as F
d = torch.Tensor([[1,2],[3,4]])
e = F.softmax(c,dim = 1)
e[0].sum()

tensor(1.)

In [8]:
a = torch.Tensor([1,2,3,4,5,6])
b = torch.Tensor([1])

In [9]:
torch.cat((a,b))

tensor([1., 2., 3., 4., 5., 6., 1.])

In [19]:
e = torch.nn.Parameter(torch.randn(1), requires_grad=True)
e2 = torch.nn.Parameter(torch.randn(1), requires_grad=True)
e3 = torch.nn.Parameter(torch.randn(1), requires_grad=True)
x = torch.randn(65)

In [16]:
(e * x).shape

torch.Size([16, 65])

In [21]:
torch.cat([e,e2,e3])

tensor([ 0.7192, -0.0276, -1.8518], grad_fn=<CatBackward>)

In [ ]:
import json
with open('pic/loss.json','w') as file_obj:
        data = json.load(file_obj)

In [ ]:
import torch
criterition = torch.nn.MSELoss()